/run/verbose 0
/event/verbose 0
/tracking/verbose 0
/acc/X1 50 mm
/acc/X2 50 mm
/acc/Y1 50 mm
/acc/Y2 50 mm
/general/dosefile /home/wakita/g4work/clinac/run1
#/general/nMax 10000
#/general/bSave false
#/general/bUsePS false 
#/general/PSname data/20x20.dat
/killer/gamma 0 MeV
/killer/e- 0 MeV
/killer/e+ 0 MeV
/killer/neutron 0 MeV
/biasing/setSplittingFactor 20
/run/beamOn 250000000 
#/run/beamOn 100000000 
#/run/beamOn 100000000 
#/run/beamOn 100000000 
#/run/beamOn 100000000 
#/run/beamOn 100000000 
#/run/beamOn 100000000 
#/run/beamOn 100000000 
#/run/beamOn 100000000 
#/run/beamOn 100000000 
